### PR TITLE
Provide NNS domain expiration in `register`

### LINKED ISSUE #259: Check admin in `Renew`
https://github.com/neo-project/non-native-contracts/pull/21

### PR DESCRIPTION
**Pull request by fyrchik**
Also, close #259 .

### CODE REVIEW

**Comment by carpawell** [comment]
tests failed?

**Comment by fyrchik** [comment]
@carpawell fixed

**Review by carpawell — APPROVED** [review]
BTW, was it a bug or why did we use constant before?

**Comment by fyrchik** [comment]
I asked @KirillovDenis , probably for convenience. It is hard to tell now.

**Pull request merged**
