### PR TITLE
rpc/nns: support NEP-18 addresses

### PR DESCRIPTION
**Pull request by roman-khimov**

### CODE REVIEW

**Review by AnnaShaleva — APPROVED** [review]

**Review by cthulhu-rider — APPROVED** [review]
code ok

@roman-khimov describe motivation in the commit pls

**Comment by roman-khimov** [comment]
Let's wait for https://github.com/neo-project/proposals/pull/133 to finally settle, but standards are good because they're standards, any compliant tooling can handle the data then.

**Review by carpawell — DISMISSED** [review]

**Comment by roman-khimov** [comment]
Rebased to fix the conflict and it can be merged now, NEP-18 is official.

**Comment by roman-khimov** [comment]
Test failure is subject to #402, this one doesn't touch contracts.

**Review by AnnaShaleva — APPROVED** [review]

**Review by cthulhu-rider — APPROVED** [review]

**Pull request merged**
