### PR TITLE
NNS update rebased

### PR DESCRIPTION
**Pull request by roman-khimov**
It's a rebase of https://github.com/nspcc-dev/neofs-contract/pull/266 with some additions. It largely intersects with https://github.com/nspcc-dev/neofs-contract/pull/419, but has two additional ones. Not intended to be merged immediately.

### CODE REVIEW

**Comment by roman-khimov** [comment]
After #419 merge this completely substitutes #266 with the only two changes left.

**Comment by carpawell** [comment]
Rebase?

**Comment by roman-khimov** [comment]
Doesn't matter much at this stage.

**Comment by carpawell** [comment]
Is it post-release?

**Comment by roman-khimov** [comment]
That's why it's not a part of #419, see above.

**Comment by carpawell** [comment]
I see it (was) based on #419 and has some additional changes but I do not see an explanation as to why not add it to the release. Dont mind though.

**Comment by roman-khimov** [comment]
Because of API changes, https://github.com/nspcc-dev/neofs-contract/pull/266#pullrequestreview-1638131153.

**Review by carpawell — COMMENTED** [review]
Smth should be done here for sure.

**Comment by roman-khimov** [comment]
The main motivation here is https://github.com/nspcc-dev/neo-go/issues/2795. It's not related to #442/C#, btw, since C# interfaces for these methods are very much different. If we're to solve https://github.com/nspcc-dev/neo-go/issues/2795 this becomes irrelevant, I think.

**Review by carpawell — APPROVED** [review]
Does not do things worse.

**Pull request merged**
